name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Install Bun in its default path ($HOME/.bun)
      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash

      # Verify Bun installation by calling it from the installation path
      - name: Verify Bun Version
        run: ~/.bun/bin/bun --version

      # Remove node_modules and package-lock.json before installing
      - name: Clean up node_modules and package-lock
        run: |
          rm -rf node_modules package-lock.json

      # Install dependencies using Bun from the installation path
      - name: Install dependencies with Bun
        run: ~/.bun/bin/bun install 

      # Build using Bun from the installation path
      - name: Build Project with Bun
        run: ~/.bun/bin/bun run build

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_PEBBLE_070F0A50F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          deployment_action: "upload"
          config_file_location: "/"
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_PEBBLE_070F0A50F }}
          action: "close"
        env:
          VITE_API_SERVER_URL: ${{ secrets.REACT_API_URL }}