# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - floatweb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install Bun in its default path ($HOME/.bun)
      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash

      # Verify Bun installation by calling it from the installation path
      - name: Verify Bun Version
        run: ~/.bun/bin/bun --version

      # Remove node_modules and package-lock.json before installing
      - name: Clean up node_modules and package-lock
        run: |
          rm -rf node_modules package-lock.json

      # Install dependencies using Bun from the installation path
      - name: Install dependencies with Bun
        run: ~/.bun/bin/bun install 

      # Build using Bun from the installation path
      - name: Build Project with Bun
        run: ~/.bun/bin/bun run build

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Set environment variable
        run: echo "VITE_API_SERVER_URL=${{secrets.REACT_API_URL}}" >> $GITHUB_ENV

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FEBFB44E58EF45B6A28BC13610847326 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CE16285CADB44910BD2F4758ECF77E99 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_99A01F00599D4D26B99804BFAE897DE4 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'floatweb'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

